"""Generate docs/CATALOG.md from the connector catalog, so the documented
list can never drift from the code. Run it to regenerate; run with --check
in CI to fail if the committed file is stale. Stdlib only."""

from __future__ import annotations

import sys
from pathlib import Path

# Import the catalog data without needing any optional extras.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))
from hallpass.catalog import OAUTH, SERVICES  # noqa: E402

DOC = Path(__file__).resolve().parent.parent / "docs" / "CATALOG.md"


def _auth_label(auth: object) -> str:
    if isinstance(auth, tuple):
        return f"{auth[0]}:{auth[1]}"
    return str(auth)


def render() -> str:
    names = sorted(SERVICES)
    total_tools = sum(len(SERVICES[n].endpoints) for n in names)
    lines = [
        "# Connector catalog",
        "",
        "Auto-generated by `scripts/gen_catalog.py` from `src/hallpass/catalog.py`.",
        "Do not edit by hand; run the script to regenerate.",
        "",
        f"**{len(names)} services, {total_tools} tools; "
        f"{len(OAUTH)} with a prewired OAuth flow.** "
        "Load one with `catalog.load(name)` or all non-per-tenant ones with "
        "`catalog.load_all()`. Per-tenant services (marked) need "
        "`catalog.load(name, base_url=...)`. Services marked `oauth` can be "
        "connected with `catalog.oauth_provider(name, ...)` + `OAuthConnect`.",
        "",
    ]
    for name in names:
        svc = SERVICES[name]
        tenant = " (per-tenant: pass `base_url`)" if svc.requires_base_url else ""
        oauth = "  oauth: yes" if name in OAUTH else ""
        base = svc.base_url or "<your tenant host>"
        lines.append(f"## {name}{tenant}")
        lines.append("")
        lines.append(f"- base: `{base}`  auth: `{_auth_label(svc.auth)}`{oauth}")
        for ep in svc.endpoints:
            scopes = ", ".join(sorted(ep.scopes)) or "-"
            lines.append(
                f"- `{ep.name}` ({ep.method} {ep.path}) - {ep.description} "
                f"[scopes: {scopes}]"
            )
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    content = render()
    check = "--check" in sys.argv
    if check:
        current = DOC.read_text(encoding="utf-8") if DOC.exists() else ""
        if current != content:
            print(
                "docs/CATALOG.md is stale; run: python scripts/gen_catalog.py",
                file=sys.stderr,
            )
            return 1
        print("docs/CATALOG.md is up to date")
        return 0
    DOC.parent.mkdir(parents=True, exist_ok=True)
    DOC.write_text(content, encoding="utf-8")
    print(f"wrote {DOC} ({len(SERVICES)} services)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
